[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| \.rst
| \.txt
| _build
| buck-out
| build
| dist

# The following are specific to Black, you probably don't want those.
| blib2to3
| tests/data
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3  # Ensures multi-line formatting
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79  # Match Black's default line length
